# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-14 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('8:00', '8am'), ('8:30', '8:30am'), ('9:00', '9am'), ('9:30', '9:30am'), ('10:00', '10am'), ('10:30', '10:30am'), ('11:00', '11am'), ('11:30', '11:30am'), ('12:00', '12pm'), ('12:30', '12:30pm'), ('1:00', '1pm'), ('1:30', '1:30pm'), ('2:00', '2pm'), ('2:30', '2:30pm'), ('3:00', '3pm'), ('3:30', '3:30pm'), ('4:00', '4pm'), ('4:30', '4;30pm'), ('5:00', '5pm')], default='8:00', max_length=5)),
                ('duration', models.CharField(choices=[('30', '30 minutes'), ('60', '1 hour')], default='30', max_length=2)),
                ('date', models.DateField(default=datetime.date(2016, 10, 14))),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Doctor')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Hospital')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Patient')),
            ],
        ),
    ]
