# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-21 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_auto_20161019_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2016, 10, 21)),
        ),
    ]
