# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-26 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0003_auto_20161021_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='location',
            new_name='hospital',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
