# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0004_auto_20161026_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('8:00', '8am'), ('8:30', '8:30am'), ('9:00', '9am'), ('9:30', '9:30am'), ('10:00', '10am'), ('10:30', '10:30am'), ('11:00', '11am'), ('11:30', '11:30am'), ('12:00', '12pm'), ('12:30', '12:30pm'), ('1:00', '1pm'), ('1:30', '1:30pm'), ('2:00', '2pm'), ('2:30', '2:30pm'), ('3:00', '3pm'), ('3:30', '3:30pm'), ('4:00', '4pm'), ('4:30', '4:30pm'), ('5:00', '5pm')], default='8:00', max_length=5),
        ),
    ]
