# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-06 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0006_auto_20161104_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('8:00 am', '8:00 am'), ('8:30 am', '8:30 am'), ('9:00 am', '9:00 am'), ('9:30 am', '9:30 am'), ('10:00 am', '10:00 am'), ('10:30 am', '10:30 am'), ('11:00 am', '11:00 am'), ('11:30 am', '11:30 am'), ('12:00 pm', '12:00 pm'), ('12:30 pm', '12:30 pm'), ('1:00 pm', '1:00 pm'), ('1:30 pm', '1:30 pm'), ('2:00 pm', '2:00 pm'), ('2:30 pm', '2:30 pm'), ('3:00 pm', '3:00 pm'), ('3:30 pm', '3:30 pm'), ('4:00 pm', '4:00 pm'), ('4:30 pm', '4:30 pm'), ('5:00 pm', '5:00 pm')], default='8:00', max_length=8),
        ),
    ]
