# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-27 12:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(message='Address does not match accepted format; no special characters allowed', regex='^(\\w|\\s)+$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height_ft',
            field=models.CharField(default='', max_length=1, validators=[django.core.validators.RegexValidator(message="Height must be entered in the format: '9'", regex='^\\+?1?\\d{1,1}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height_inch',
            field=models.CharField(default='', max_length=2, validators=[django.core.validators.RegexValidator(message="Height must be entered in the format: '99'", regex='^\\+?1?\\d{1,2}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ice_name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Address does not match accepted format; no special characters allowed', regex='^[a-zA-Z]+\\s[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ice_phone',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message="Insurance number must be entered in the format: '999999999'. Only to 9 digits allowed.", regex='^\\+?1?\\d{9,9}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10,10}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.CharField(default='', max_length=3, validators=[django.core.validators.RegexValidator(message="Weight must be entered in the format: '999'", regex='^\\+?1?\\d{1,3}$')]),
        ),
    ]
