# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-04 17:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20161027_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ice_name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Name does not match accepted format; no special characters allowed', regex='^[a-zA-Z]+\\s[a-zA-Z]+$')]),
        ),
    ]
