# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-06 20:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20161104_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height_ft',
            field=models.CharField(default='', max_length=1, validators=[django.core.validators.RegexValidator(message="Height must be entered in the format: '9'", regex='^\\d{1}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height_inch',
            field=models.CharField(default='', max_length=2, validators=[django.core.validators.RegexValidator(message="Height must be entered in the format: '99'", regex='^\\d{1,2}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ice_phone',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '(999) 999-9999'. 10 digits are required.", regex='^\\(?\\d{3}\\)?[ -]\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message="Insurance number must be entered in the format: '999999999'. Only to 9 digits allowed.", regex='^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '(999) 999-9999'. 10 digits are required.", regex='^\\(?\\d{3}\\)?[ -]\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.CharField(default='', max_length=3, validators=[django.core.validators.RegexValidator(message="Weight must be entered in the format: '999'", regex='^\\d{1,3}$')]),
        ),
    ]
