# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-08 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20161106_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharge',
            field=models.BooleanField(default=False),
        ),
    ]
