# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-16 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20161107_2016'),
        ('Records', '0002_auto_20161116_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Doctor'),
        ),
        migrations.AddField(
            model_name='testresults',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Patient'),
        ),
        migrations.AddField(
            model_name='testresults',
            name='viewable',
            field=models.BooleanField(default=False),
        ),
    ]
