# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-16 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0003_auto_20161116_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='results',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='test_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
