# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-16 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0004_auto_20161116_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
