# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-29 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0005_auto_20161116_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateField(default=datetime.date(2016, 11, 29)),
        ),
    ]
