# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-11 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0006_auto_20161107_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2016, 11, 11))),
                ('drug', models.CharField(default='', max_length=50)),
                ('dosage', models.CharField(default='', max_length=20)),
                ('instructions', models.CharField(default='', max_length=200)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Doctor')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Hospital')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Patient')),
            ],
        ),
    ]
